### ISSUE TITLE
Unable to open pull request

### ISSUE THREAD

**Issue by pboling** [grosser/open_id_authentication#5]
I think this is a bug in GitHub itself.

Also unable to view commits index.

**Comment by grosser** [comment]
nothing special about this repo afaik ... try again in a day or so, otherwise github support ...
if you have a fork + branch ready I can try and make the PR

**Comment by pboling** [comment]
I rebuilt the whole stack, modernizing it all significantly.

Needed to pickup all the Ruby 2.7+ and Rails 5+ fixes from the fork networks, and add working CI (GitHub Actions) in a very short period of time. Not expecting any of this to be merged, but happy to talk about how we could use the work I've done if you're interested.

Dependencies:

`ruby-openid` => `ruby-openid2` = https://github.com/grosser/ruby-openid/pull/1
`rack-openid` => `rack-openid2` = https://github.com/grosser/rack-openid/pull/6

And for this repo, I want to open a PR from [here](https://github.com/VitalConnectInc/open_id_authentication2), but it is not possible, though you can try and add another data point there 😄 :
`open_id_authentication` => `open_id_authentication2` = https://github.com/VitalConnectInc/open_id_authentication2

**Comment by grosser** [comment]
ah nvm, this is just a fork itself ... best start your own fork, I'm not using this fork for anything :D

**Comment by pboling** [comment]
@grosser yes, it is a fork, but this fork repo is listed as the "homepage" of the gem on RubyGems.org, and you have push access to the gem there as well.  I think this is as canonical as it gets.

If you aren't using it anymore, I'll happily take over, and merge the streams. 👻 

https://rubygems.org/gems/open_id_authentication

**Comment by grosser** [comment]
added you as owner, have fun 👍

**Comment by pboling** [comment]
Released v2.0.1 returned to the original gem name.

Thanks!
